import type { VoucherEmitido } from '@/types'

export const CUSTOMER_LOGO_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl16SAAAAAASUVORK5CYII='

export const AGENCY_LOGO_DATA_URL =
  'data:image/webp;base64,UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEAAUAmJaQAA3AA/v89WAAAAA=='

export const AD_LOGO_DATA_URL =
  'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggNDgiPjx0ZXh0IHg9IjQiIHk9IjMyIiBmb250LXNpemU9IjI4IiBmaWxsPSIjMDA2ZjkxIj5BWlVMPC90ZXh0Pjwvc3ZnPg=='

export const G3_LOGO_DATA_URL =
  'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggNDgiPjx0ZXh0IHg9IjQiIHk9IjMyIiBmb250LXNpemU9IjI4IiBmaWxsPSIjZjU3YzAwIj5HT0w8L3RleHQ+PC9zdmc+'

export const CUSTOM_DOCUMENT_BRANDING = {
  displayName: 'Grupo Exemplo',
  logoDataUrl: CUSTOMER_LOGO_DATA_URL,
  primaryColor: '#123456',
  accentColor: '#ABCDEF',
  documentLegalName: 'Grupo Exemplo Participacoes S.A.',
  documentNumber: '12.345.678/0001-90',
} as const

export const SELF_CONTAINED_DOCUMENT_ASSETS = {
  agencyLogo: {
    src: AGENCY_LOGO_DATA_URL,
    alt: 'BBT Corporativo',
  },
  customerLogo: {
    src: CUSTOMER_LOGO_DATA_URL,
    alt: 'Grupo Exemplo',
  },
  airlineLogos: {
    AD: {
      src: AD_LOGO_DATA_URL,
      alt: 'Logomarca da Azul Linhas Aereas Brasileiras',
    },
    G3: {
      src: G3_LOGO_DATA_URL,
      alt: 'Logomarca da GOL Linhas Aereas',
    },
  },
} as const

export function completeHotelVoucher(
  overrides: Partial<VoucherEmitido> = {},
): VoucherEmitido {
  return {
    id: 'H-PARITY-001',
    numero: 'PARITY-001',
    tipo: 'Hotel',
    status: 'confirmado',
    atendimento_id: 'demand-hotel-parity',
    empresa_id: 'company-parity',
    funcionario_id: 'employee-hotel-primary',
    passageiro_nome: 'Ana Principal',
    passageiros: ['Ana Principal', 'Bruno Acompanhante'],
    hospedes_detalhes: [
      {
        nome: 'Ana Principal',
        papel: 'Responsavel',
        principal: true,
        codigo: 'VIA-101',
        documento: '12345678901',
        email: 'ana@example.com',
        telefone: '(62) 99999-1111',
        quarto: 1,
      },
      {
        nome: 'Bruno Acompanhante',
        papel: 'Acompanhante',
        codigo: 'VIA-102',
        documento: 'AB123456',
        email: 'bruno@example.com',
        quarto: 1,
      },
    ],
    empresa_nome: 'Cliente & Companhia S.A.',
    empresa_documento: '98.765.432/0001-10',
    unidade_negocio: 'Unidade Centro-Oeste',
    departamento: 'Controladoria',
    solicitante_nome: 'Bia Solicitante',
    solicitante_email: 'bia.solicitante@example.com',
    autorizadores: ['Aprovadora Um', 'Diretor Final'],
    autorizado_em: '2026-08-04T18:15:00.000Z',
    data_solicitacao: '2026-08-01T13:00:00.000Z',
    reserva_id: 'RES-HOTEL-4455',
    data_reserva: '2026-08-04T17:30:00.000Z',
    fornecedor_nome: 'Operadora & Reservas Ltda.',
    fornecedor_codigo: 'FORN-7788',
    fornecedor_endereco: 'Av. Operacional, 10',
    fornecedor_cidade: 'Goiania/GO',
    fornecedor_telefone: '(62) 3000-1000',
    fornecedor_email: 'operacao@example.com',
    canal_reserva: 'E-mail',
    hotel_nome: 'Hotel Alpha Park',
    hotel_endereco: 'Avenida Alphaville Flamboyant, 3609',
    hotel_cidade: 'Goiania/GO',
    hotel_telefone: '(62) 3257-7900',
    hotel_email: 'reservas@alphapark.example',
    hotel_categoria: 'Standard',
    tipo_apartamento: 'Double Standard',
    // Intencionalmente sem `quartos`: o documento deve reproduzir o mesmo
    // fallback visual da tela a partir dos campos legados da hospedagem.
    quartos: undefined,
    num_apartamentos: 1,
    num_hospedes: 2,
    data_checkin: '2026-09-03',
    data_checkout: '2026-09-05',
    checkin_em: '2026-09-03T17:00:00.000Z',
    checkout_em: '2026-09-05T15:00:00.000Z',
    noites: 2,
    regime: 'Cafe da manha',
    forma_pagamento_voucher: 'Faturado',
    referencia_pagamento: 'FAT-30-DIAS',
    condicoes_pagamento: 'Faturar diarias e taxas',
    prazo_cancelamento: '2026-08-31T18:00:00.000Z',
    politica_cancelamento: 'Apos o prazo, cobranca integral.',
    politica_no_show: 'No-show sujeito a 100% da hospedagem.',
    reembolsavel: false,
    localizador: 'LOC-13728',
    numero_confirmacao: 'CONF-HOTEL-9988',
    data_confirmacao: '2026-08-04T17:35:00.000Z',
    confirmado_por: 'Consultor Offline',
    valor_diaria: 330,
    taxas_diaria: 40.26,
    taxa_servico: 15,
    tarifa_total: 660,
    taxas: 80.52,
    total: 755.52,
    moeda: 'BRL',
    centro_custo: '1001 - Administracao',
    numero_solicitacao: 'OS-20260804-0004',
    observacoes: 'Chegada prevista apos 20h. Apresentar documento no check-in.',
    emitido_por_user_id: 'operator-parity',
    emitido_por_user_name: 'Operador BBT',
    created_at: '2026-08-04T17:40:00.000Z',
    ...overrides,
  }
}

export function completeAirVoucher(
  overrides: Partial<VoucherEmitido> = {},
): VoucherEmitido {
  return {
    id: 'A-PARITY-001',
    numero: 'PARITY-001',
    tipo: 'Aéreo',
    status: 'emitido',
    atendimento_id: 'demand-air-parity',
    empresa_id: 'company-parity',
    funcionario_id: 'employee-air-primary',
    passageiro_nome: 'Ana Viajante',
    passageiros: ['Ana Viajante', 'Bruno Viajante'],
    hospedes_detalhes: [
      {
        nome: 'Ana Viajante',
        papel: 'Passageira responsavel',
        principal: true,
        codigo: 'PAX-001',
        documento: '12345678901',
        email: 'ana.viajante@example.com',
      },
      {
        nome: 'Bruno Viajante',
        papel: 'Passageiro',
        codigo: 'PAX-002',
        documento: '98765432100',
        email: 'bruno.viajante@example.com',
      },
    ],
    empresa_nome: 'Cliente & Companhia S.A.',
    empresa_documento: '98.765.432/0001-10',
    unidade_negocio: 'Unidade Centro-Oeste',
    departamento: 'Diretoria Comercial',
    solicitante_nome: 'Bia Solicitante',
    solicitante_email: 'bia.solicitante@example.com',
    autorizadores: ['Aprovadora Um', 'Diretor Final'],
    autorizado_em: '2026-08-10T14:20:00.000Z',
    data_solicitacao: '2026-08-08T12:00:00.000Z',
    reserva_id: 'RES-AIR-9988',
    data_reserva: '2026-08-10T13:40:00.000Z',
    fornecedor_nome: 'Consolidadora Aerea BBT',
    fornecedor_codigo: 'CONSOL-001',
    fornecedor_endereco: 'Rua da Operacao, 100',
    fornecedor_cidade: 'Goiania/GO',
    fornecedor_telefone: '(62) 3550-0851',
    fornecedor_email: 'aereo@example.com',
    canal_reserva: 'Offline',
    cia_aerea: 'Azul Linhas Aereas Brasileiras',
    origem: 'GYN - Goiania',
    destino: 'CGH - Sao Paulo',
    data_ida: '2026-09-01T13:00:00.000Z',
    data_volta: '2026-09-05T20:00:00.000Z',
    classe: 'Economica Promocional',
    localizador: 'ABC123',
    sistema_reserva: 'SABRE',
    prazo_emissao: '2026-08-11T02:59:00.000Z',
    tarifa_referencia: 9856.52,
    rav: 25,
    rac: 15,
    cambio: 1,
    milhagem: 0,
    trechos_aereos: [
      {
        sequencia: 1,
        companhia_codigo: 'AD',
        companhia_nome: 'Azul Linhas Aereas Brasileiras',
        numero_voo: '1327',
        classe_reserva: 'Y',
        cabine: 'Economica',
        bagagens: 1,
        origem_codigo: 'GYN',
        origem_nome: 'Santa Genoveva International Airport - Goiania/GO',
        destino_codigo: 'CGH',
        destino_nome: 'Congonhas Airport - Sao Paulo/SP',
        saida_em: '2026-09-01T13:00:00.000Z',
        chegada_em: '2026-09-01T14:50:00.000Z',
      },
      {
        sequencia: 2,
        companhia_codigo: 'G3',
        companhia_nome: 'GOL Linhas Aereas',
        numero_voo: '3399',
        classe_reserva: 'V',
        cabine: 'Economica',
        bagagens: 1,
        origem_codigo: 'CGH',
        origem_nome: 'Congonhas Airport - Sao Paulo/SP',
        destino_codigo: 'GYN',
        destino_nome: 'Santa Genoveva International Airport - Goiania/GO',
        saida_em: '2026-09-05T20:00:00.000Z',
        chegada_em: '2026-09-05T21:45:00.000Z',
      },
    ],
    bilhetes_aereos: [
      {
        passageiro_nome: 'Ana Viajante',
        passageiro_ordem: 1,
        passageiro_codigo: 'PAX-001',
        numero_bilhete: '5771234567890',
        companhia_codigo: 'AD',
        companhia_nome: 'Azul Linhas Aereas Brasileiras',
      },
      {
        passageiro_nome: 'Bruno Viajante',
        passageiro_ordem: 2,
        passageiro_codigo: 'PAX-002',
        numero_bilhete: '1270987654321',
        companhia_codigo: 'G3',
        companhia_nome: 'GOL Linhas Aereas',
      },
    ],
    numero_confirmacao: 'AIR-CONF-9988',
    data_confirmacao: '2026-08-10T13:45:00.000Z',
    confirmado_por: 'Consultor Aereo',
    tarifa_total: 3678.74,
    taxas: 110.96,
    taxa_servico: 35,
    total: 3864.70,
    moeda: 'BRL',
    centro_custo: '2002 - Comercial',
    numero_solicitacao: 'OS-20260810-0001',
    prazo_cancelamento: '2026-08-11T02:59:00.000Z',
    politica_cancelamento: 'Tarifa nao reembolsavel apos a emissao.',
    politica_no_show: 'No-show sujeito as regras de cada companhia.',
    reembolsavel: false,
    observacoes: 'Apresentar-se no aeroporto com antecedencia minima de duas horas.',
    emitido_por_user_id: 'operator-parity',
    emitido_por_user_name: 'Operador Aereo BBT',
    created_at: '2026-08-10T13:50:00.000Z',
    ...overrides,
  }
}
