import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (file: string) => readFileSync(resolve(process.cwd(), file), 'utf8')

describe('offline air reservation and emission integration', () => {
  it('copies the approved quote into immutable structured reservation rows', () => {
    const service = read('lib/server/offline-travel-service.ts')
    expect(service).toContain('persistApprovedAirReservation')
    expect(service).toContain('insert into air_reservation_details')
    expect(service).toContain('insert into air_reservation_segments')
    expect(service).toContain('source_quote_option_id')
    expect(service).toContain("quote_segment.metadata || $4::jsonb")
    expect(service).toContain('OFFLINE_APPROVED_AIR_QUOTE_SEGMENTS_MISSING')
  })

  it('validates canonical air segment timestamps and keeps legacy snapshots compatible', () => {
    const service = read('lib/server/offline-travel-service.ts')
    expect(service).toContain('approvedAirSegmentDepartureAt(segment)')
    expect(service).toContain('approvedAirSegmentArrivalAt(segment)')
    expect(service).toContain('segment.departsAt || segment.departureAt')
    expect(service).toContain('segment.arrivesAt || segment.arrivalAt')
    expect(service).toContain('dateTimeOrNull(snapshotOption.startsAt) || approvedAirSegmentDepartureAt(firstSegment)')
    expect(service).toContain('dateTimeOrNull(snapshotOption.endsAt) || approvedAirSegmentArrivalAt(lastSegment)')
  })

  it('records one ticket per passenger and marks every reserved segment as issued', () => {
    const service = read('lib/server/offline-travel-service.ts')
    expect(service).toContain('persistAirEmissionTickets')
    expect(service).toContain('insert into air_emission_tickets')
    expect(service).toContain('airTicketsFromIssue')
    expect(service).toContain("set status = 'issued'")
    expect(service).not.toContain('distributedMinorAmount')
    expect(service).toContain('matchAirTicketsToTravelers')
    expect(service).toContain('demand_traveler_id')
    expect(service).toContain('demandTravelerId')
    expect(service).toContain('OFFLINE_AIR_TICKET_TRAVELER_REQUIRED')
    expect(service).toContain('OFFLINE_AIR_TICKET_DUPLICATE')
    expect(service).toContain('OFFLINE_AIR_TICKETS_PASSENGER_COUNT_MISMATCH')
    expect(service).toMatch(/ticket\.ticketNumber,[\s\S]*airline\.airline_name,[\s\S]*0,[\s\S]*0,[\s\S]*0,/)
  })

  it('carries all demand passengers into the immutable choice and reservation snapshots', () => {
    const quoteService = read('lib/server/offline-quote-service.ts')
    const operationService = read('lib/server/offline-travel-service.ts')
    expect(quoteService).toContain('air_passengers')
    expect(quoteService).toContain('passengers: demandPassengerSnapshots')
    expect(operationService).toContain('snapshotDemand.passengers')
    expect(operationService).toContain('passengers: passengerNames')
  })

  it('keeps approved itinerary and prices locked while exposing operational fields', () => {
    const form = read('components/travel/offline-travel-operation-form.tsx')
    const demandService = read('lib/server/demand-service.ts')
    expect(form).toContain('OfflineAirOperationFields')
    expect(form).toContain('loadSelectedAirQuote')
    expect(form).toContain('applySelectedAirQuote')
    expect(form).toContain("offlineServiceFromDemand(String(demand.tipo_servico || ''))")
    expect(form).toContain("moneyToMinorUnits(option.pricing.taxes || '0')")
    expect(form).not.toContain('Number(option.pricing.taxes || 0)')
    expect(form).toContain('selectedAt: serverOption.selectedAt')
    expect(form).toContain('approvedAt: serverOption.approvedAt')
    expect(form).not.toContain("approvedAt: serverOption.approvalStatus === 'approved' ? new Date()")
    expect(demandService).toContain('tipo_servico: offlineLegacyServiceType(row.service_type)')
    expect(form).toContain('airTickets: serviceKey')
    expect(form).toContain('Gerar voucher completo')
    expect(form).toContain('A escolha aérea ainda não possui uma aprovação concluída')
  })

  it('renders all air segments and passenger tickets on the voucher', () => {
    const service = read('lib/server/offline-travel-service.ts')
    const page = read('app/dashboard/vouchers/[id]/page.tsx')
    const assistantPdf = read('lib/assistant/pdf.ts')
    const documentModel = read('lib/vouchers/document-model.ts')
    const voucherDocument = read('components/vouchers/voucher-document.tsx')
    const documentStyles = read('lib/vouchers/document-styles.ts')
    const types = read('types/index.ts')
    expect(service).toContain('loadAirVoucherData')
    expect(service).toContain('trechos_aereos')
    expect(service).toContain('bilhetes_aereos')
    expect(service).toContain('passageiro_ordem')
    expect(service).toContain('passageiro_codigo')
    expect(service).toContain('employee.identification_code')
    expect(page).toContain('<VoucherDocument model={documentModel} assets={documentAssets} />')
    expect(assistantPdf).toContain('VoucherDocument({ model, assets })')
    expect(documentModel).toContain('(voucher.trechos_aereos || []).map')
    expect(documentModel).toContain('(voucher.bilhetes_aereos || []).map')
    expect(documentModel).toContain('ticket.passageiro_ordem')
    expect(documentModel).toContain('ticket.passageiro_codigo')
    expect(voucherDocument).toContain('title="Itinerário aéreo"')
    expect(voucherDocument).toContain('title="Bilhetes emitidos"')
    expect(types).toContain('interface VoucherTrechoAereo')
    expect(types).toContain('interface VoucherBilheteAereo')
    expect(page).toContain('resolveAirlineBrand(code)')
    expect(page).toContain('brand.logoPath')
    expect(voucherDocument).toContain('assets.airlineLogos?.[normalizedCode]')
    expect(voucherDocument).toContain('data-voucher-logo="airline"')
    expect(documentStyles).toContain('@media print')
    expect(documentStyles).toContain('page-break-inside: avoid')
  })
})
